name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Git Commit Hash
        id: git_commit_hash
        run: echo ::set-output name=commit_hash::$(git log -1 --format='%h')
        
        
        #      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            richpeople/ip2regionapi:latest
            richpeople/ip2regionapi:${{ steps.git_commit_hash.outputs.commit_hash }}
            
