name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            richpeople/ip2regionapi:latest
            richpeople/ip2regionapi:$(git log -1 --pretty=%h)  # 使用短提交哈希作为标签
            # richpeople/ip2regionapi:$(git log -1 --pretty=%cd --date=format:'%Y%m%d%H%M%S')  # 使用提交日期作为标签

